apiVersion: v1
kind: ConfigMap
metadata:
  name: gymapp-config
  namespace: gymapp
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gym?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: root
  APP_JWT_EXPIRATION_SECONDS: "86400"
  GOOGLE_CLIENT_ID: YOUR_GOOGLE_CLIENT_ID
  FACEBOOK_CLIENT_ID: YOUR_FACEBOOK_CLIENT_ID
  TWITTER_CLIENT_ID: YOUR_TWITTER_CLIENT_ID
