apiVersion: v1
kind: Secret
metadata:
  name: gymapp-secret
  namespace: gymapp
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: Sample-pass
  APP_JWT_SECRET: change-this-to-a-very-long-random-secret-key-at-least-32-bytes
  GOOGLE_CLIENT_SECRET: YOUR_GOOGLE_CLIENT_SECRET
  FACEBOOK_CLIENT_SECRET: YOUR_FACEBOOK_CLIENT_SECRET
  TWITTER_CLIENT_SECRET: YOUR_TWITTER_CLIENT_SECRET
