apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gymapp.fullname" . }}-secret
  labels:
    {{- include "gymapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | quote }}
  APP_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  FACEBOOK_CLIENT_SECRET: {{ .Values.secrets.facebookClientSecret | quote }}
  TWITTER_CLIENT_SECRET: {{ .Values.secrets.twitterClientSecret | quote }}
