apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gymapp-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: gymapp=theprocastinator/decentralised-gym
    argocd-image-updater.argoproj.io/gymapp.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/gymapp.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/gymapp.update-strategy: newest-build
    argocd-image-updater.argoproj.io/gymapp.allow-tags: regexp:^[0-9]{14}-[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/imanishpr/decentralised-gym.git
    targetRevision: codex/phase1-auth-jwt-swagger-actuator
    path: helm/gymapp
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gymapp-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
