apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gymapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/imanishpr/decentralised-gym.git
    targetRevision: codex/phase1-auth-jwt-swagger-actuator
    path: helm/gymapp
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gymapp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
